// Extension entry point. Generic C-tier (family module) orchestration:
//   1. load locale
//   2. register a standalone sidebar tab (fallback)
//   3. create the provider and register it with WorkspaceKit
//   4. when a WorkspaceKit host claims the provider, drop the standalone tab
//
// You normally do NOT edit this file — change identity in ui/provider.js and
// build your UI in ui/module-view.js.

import { app } from "../../scripts/app.js";
import { configureI18n, t } from "./foundation/i18n.js";
import { registerWorkspaceKitProvider } from "./integrations/workspacekit-adapter.js";
import { createProvider } from "./ui/provider.js";
import { registerStandalonePanel, unregisterStandalonePanel } from "./ui/standalone-panel.js";

const EXTENSION_NAME = "WorkspaceKit.ExampleFamilyModule"; // CHANGE ME

app.registerExtension({
  name: EXTENSION_NAME,
  async setup() {
    await configureI18n(app);

    // Register the standalone fallback first so the plugin is usable even if
    // WorkspaceKit never loads. It is removed only after a host confirms it can
    // render the provider (via onHostClaimed), preventing a duplicate entry.
    registerStandalonePanel({ app, translate: t });

    const provider = createProvider({
      app,
      translate: t,
      onHostClaimed: () => unregisterStandalonePanel(app),
    });

    const registration = registerWorkspaceKitProvider(provider);
    if (!registration.ok) {
      console.warn("[WorkspaceKit Example] provider registration was not accepted:", registration.code);
    }
  },
});
