// WorkspaceKit built-in i18n fallback strings. Pure static data: the
// translation table used when no locale asset is loaded. Consumed by
// core/i18n.js via configureI18n(app, FALLBACK_STRINGS) in entry.js.
// No logic, no lookups — the lookup/merge behavior lives in core/i18n.js.

export const FALLBACK_STRINGS = {
  "zh-CN": {
    "workspace.title": "WK 面板",
    "workspace.tooltip": "ComfyUI WorkspaceKit（WK 面板）",
    "workspace.tab.workflows": "工作流",
    "workspace.tab.nodes": "节点",
    "workspace.tab.templates": "模板",
    "settings.title": "设置",
    "settings.nav.common": "常用",
    "settings.nav.workflows": "工作流",
    "settings.nav.templates": "模板",
    "settings.nav.groups": "编组",
    "settings.nav.shortcuts": "快捷键",
    "settings.nav.appearance": "外观",
    "settings.nav.advanced": "高级",
    "settings.shortcuts": "快捷键",
    "settings.behavior": "打开行为",
    "settings.workflowSettings": "工作流行为",
    "settings.templateSettings": "模板行为",
    "settings.groupSettings": "编组",
    "settings.groupSettingsHelp": "集中管理 WorkspaceKit 编组的启用、创建、解散和鼠标手势。",
    "settings.recentWorkflows": "打开记录数量",
    "settings.topbarSaveButton": "在顶部工具栏显示保存按钮",
    "topbar.save": "保存工作流",
    "topbar.saveUnsaved": "保存工作流（有未保存的改动）",
    "settings.panelOpacity": "面板透明度",
    "settings.panelGlass": "玻璃背景",
    "settings.panelBlur": "背景模糊",
    "settings.backgroundEffect": "背景效果",
    "settings.transparentBackground": "透明背景",
    "settings.glassBackground": "磨砂玻璃",
    "settings.nodeCache": "节点缓存",
    "settings.panelIntegrations": "插件集成",
    "settings.statusHelp": "显示底部状态提示",
    "settings.extensionSettings": "扩展设置",
    "settings.panelIntegrationsEnabled": "允许扩展合并到侧边栏",
    "settings.panelIntegrationsHelp": "关闭后，兼容扩展会在下次刷新页面后保持独立入口；重新开启并刷新后，会再次合并到 WorkspaceKit。",
    "settings.about": "关于",
    "settings.ctrlG": "启用 WorkspaceKit 编组",
    "settings.ctrlGHelp": "开启后，Ctrl+G 会替换 ComfyUI 默认编组。",
    "settings.altCOpenTemplates": "Alt+C 保存后自动打开模板",
    "settings.closeSameModule": "重复按当前标签快捷键时关闭面板",
    "settings.shortcuts.workflow": "工作流面板",
    "settings.shortcuts.nodes": "节点面板",
    "settings.shortcuts.templates": "模板面板",
    "settings.shortcuts.extension": "置顶扩展面板",
    "settings.shortcuts.saveTemplate": "保存模板",
    "settings.shortcuts.createGroup": "WorkspaceKit 编组",
    "settings.shortcuts.ungroup": "取消编组",
    "settings.shortcuts.shiftLeftClickKey": "Ctrl + 左键",
    "settings.shortcuts.toggleGroupIgnore": "切换是否忽略编组",
    "settings.shortcutsHelp": "常用快捷键",
    "settings.groupPointerActions.group.disabled": "关闭",
    "settings.groupPointerRestore": "恢复默认手势",
    "settings.moduleShortcutsHelp": "关闭某一项后，对应组合键会交还给 ComfyUI 或浏览器。Shift + 4 会打开当前置顶的扩展面板。",
    "settings.moduleShortcuts.workflows": "启用 Shift + 1（工作流）",
    "settings.moduleShortcuts.nodes": "启用 Shift + 2（节点）",
    "settings.moduleShortcuts.templates": "启用 Shift + 3（模板）",
    "settings.moduleShortcuts.extension": "启用 Shift + 4（置顶扩展）",
    "settings.cacheCount": "缓存节点：{count}",
    "settings.cacheUpdated": "更新时间：{time}",
    "settings.cacheEmpty": "暂无缓存",
    "settings.clearNodeCache": "清空节点缓存",
    "settings.nodeCacheCleared": "节点缓存已清空",
    "settings.close": "关闭",
    "settings.version": "版本：{version}",
    "settings.versionLoading": "读取中…",
    "settings.versionUnavailable": "不可用",
    "settings.github": "GitHub：ZiYao00/ComfyUI-WorkspaceKit",
    "confirm.cancel": "取消",
    "confirm.dissolve": "解散",
    "confirm.flatten": "全部拍平",
    "confirm.delete": "删除",
    "confirm.moveToSystemTrash": "移到系统回收站",
    "confirm.emptyTrash": "清空回收站",
    "trash.systemDeleteTitle": "移到系统回收站",
    "trash.emptyTitle": "清空 WorkspaceKit 回收站",
    "trash.moveToSystem": "清空到系统回收站",
    "trash.moveAllToSystemShort": "清空到系统回收站",
    "status.folderDissolved": "已解散文件夹",
    "status.folderFlattened": "已拍平文件夹",
    "status.folderDissolvedRenamed": "已解散文件夹；{count} 个项目因重名已自动加序号",
    "status.folderFlattenedRenamed": "已拍平文件夹；{count} 个文件因重名已自动加序号",
    "status.systemTrashPartial": "部分项目移到系统回收站失败：{count} 个。{details}",
    "workflows.title": "工作流",
    "workflows.current": "当前工作流",
    "workflows.recent": "打开",
    "workflows.browse": "浏览",
    "workflows.view.all": "全部",
    "workflows.view.favorites": "收藏",
    "workflows.addFavorite": "收藏工作流",
    "workflows.removeFavorite": "取消收藏工作流",
    "workflows.favoriteAdded": "已收藏工作流",
    "workflows.favoriteRemoved": "已取消收藏工作流",
    "workflows.currentEmpty": "未从 Workflows2 打开工作流",
    "workflows.removeRecent": "从打开记录移除",
    "workflows.close": "关闭工作流",
    "workflows.saveCurrent": "保存当前工作流",
    "workflows.unsavedChanges": "未保存的更改",
    "workflows.fileMenu": "文件",
    "workflows.fileMenuTitle": "当前工作流文件操作",
    "workflows.fileNewWorkflow": "新建工作流",
    "workflows.fileNewFolder": "新建文件夹",
    "workflows.fileSave": "保存",
    "workflows.fileSaveAs": "另存为",
    "workflows.fileExport": "导出工作流",
    "workflows.fileExportApi": "导出 API 工作流",
    "workflows.closeUnsavedTitle": "关闭未保存的工作流",
    "workflows.closeUnsavedMessage": "“{name}”有未保存的更改。",
    "workflows.closeSave": "保存并关闭",
    "workflows.closeDiscard": "不保存并关闭",
    "toolbar.openWorkflow": "导入",
    "row.copy": "复制工作流",
    "nodes.title": "节点",
    "nodes.status": "{count} 个节点",
    "nodes.searchPlaceholder": "搜索节点",
    "nodes.categoryBookmarked": "收藏",
    "nodes.categoryComfy": "Comfy",
    "nodes.categoryExtensions": "扩展",
    "nodes.view.bookmarked": "收藏",
    "nodes.view.comfy": "Comfy",
    "nodes.view.extensions": "扩展",
    "nodes.moveToFavoriteRoot": "移到收藏根位置",
    "nodes.moveToFavoriteRootTitle": "拖拽收藏节点到这里，移到收藏根位置",
    "nodes.loadingDefinitions": "正在加载节点信息，插件较多时首次打开可能需要几秒。",
    "nodes.updatingDefinitions": "正在后台更新完整节点信息...",
    "nodes.officialCategory.3d": "3D",
    "nodes.officialCategory.advanced": "高级",
    "nodes.officialCategory.audio": "音频",
    "nodes.officialCategory.conditioning": "条件",
    "nodes.officialCategory.experimental": "实验性",
    "nodes.officialCategory.image": "图像",
    "nodes.officialCategory.latent": "潜空间",
    "nodes.officialCategory.model": "模型",
    "nodes.officialCategory.text": "文本",
    "nodes.officialCategory.video": "视频",
    "search.placeholder": "搜索工作流",
    "root.move": "移到根目录",
    "status.loading": "正在加载...",
    "status.error": "错误：{message}",
    "status.openedWorkflowFile": "已打开工作流文件",
    "status.workflowSaved": "工作流已保存",
    "status.workflowCopied": "已复制工作流：{name}",
    "status.workflowRenameTargetExists": "已有同名工作流。",
    "status.workflowRenameSourceMissing": "找不到原工作流文件。",
    "status.workflowSaveMismatch": "只能保存当前打开的工作流",
    "status.workflowSerializeUnavailable": "当前 ComfyUI 前端不支持直接保存当前画布",
    "workflows.sort.nameAsc": "名称 A-Z",
    "workflows.sort.nameDesc": "名称 Z-A",
    "workflows.sort.updatedDesc": "修改时间新到旧",
    "workflows.sort.updatedAsc": "修改时间旧到新",
    "workflows.customOrder": "自定义顺序",
    "workflows.folderFirst": "优先文件夹",
    "workflows.sortTitle": "工作流排序：{sort}。点击打开菜单。",
    "workflows.sortMenu": "排序",
    "workflows.reorderHandle": "拖动调整顺序",
    "font.size": "列表字号",
    "search.clear": "清空搜索",
    "nodes.customOrder": "自定义顺序",
    "nodes.reorderHandle": "拖动调整顺序",
    "nodes.defaultGroupName": "新建分组",
    "nodes.previewEnable": "打开节点预览",
    "nodes.previewDisable": "关闭节点预览",
    "nodes.previewOverflowInputs": "其余 {count} 个输入",
    "nodes.previewOverflowWidgets": "其余 {count} 个参数",
    "nodes.previewOverflowOutputs": "其余 {count} 个输出",
    "nodes.previewKindImage": "图像",
    "nodes.previewKindAudio": "音频",
    "nodes.previewKindVideo": "视频",
    "nodes.previewKind3d": "3D",
    "nodes.previewKindText": "文本",
    "nodes.uiScaleTitle": "列表字号",
    "nodes.categoryUnknown": "来源未知",
    "nodes.deleteGroupTitle": "删除收藏分组",
    "nodes.dissolveGroupTitle": "解散此分组及全部子分组；保留内部所有收藏节点。",
    "nodes.deleteGroupContentsTitle": "删除此分组，并取消其中及子分组内的所有收藏节点。",
    "menu.newSubfolder": "新建子文件夹",
    "menu.flattenFolder": "全部拍平",
    "row.openLocation": "打开工作流位置",
    "folder.personalize": "个性化",
    "folder.dissolveTitle": "取消此文件夹；内部文件和子文件夹会保留并提升到上一级。",
    "folder.flattenTitle": "移除此文件夹及其下所有子文件夹；内部所有文件会全部提升到上一级。",
    "folder.deleteTitle": "将此文件夹及其内部内容移到回收站。",
    "folder.changeIcon": "修改图标",
    "folder.changeColor": "修改颜色",
    "folder.resetStyle": "重置样式",
    "folder.personalizeTitle": "个性化",
    "folder.personalizePreview": "预览",
    "folder.personalizeIcon": "图标",
    "folder.personalizeColor": "颜色",
    "folder.personalizeApply": "应用",
    "folder.personalizeReset": "重置",
    "folder.personalizeCancel": "取消",
    "folder.personalizeDefault": "默认",
    "folder.defaultName": "新建文件夹",
    "folder.promptIcon": "输入 PrimeIcons class（如 pi pi-folder）或 emoji。留空使用默认图标。",
    "folder.promptColor": "输入颜色，如 #8ab4f8。留空使用默认颜色。",
    "canvasGroups.title": "编组",
    "canvasGroups.status": "{count} 个编组",
    "canvasGroups.searchPlaceholder": "搜索编组",
    "canvasGroups.create": "用当前选中节点创建编组",
    "canvasGroups.refresh": "刷新编组列表",
    "canvasGroups.empty": "当前工作流没有编组。",
    "canvasGroups.noMatches": "没有匹配的编组。",
    "canvasGroups.nodes": "{count} 个节点",
    "canvasGroups.locate": "定位编组",
    "canvasGroups.rename": "重命名编组",
    "canvasGroups.promptRename": "编组名称",
    "canvasGroups.toggleBypass": "绕过 / 恢复编组",
    "canvasGroups.delete": "删除编组",
    "canvasGroups.confirmDelete": "删除编组“{name}”？不会删除节点。",
    "groups.headerOpacity": "标题栏",
    "groups.actionRename": "重命名编组",
    "groups.backgroundFill": "背景",
    "groups.colorPreset": "配色预设",
    "groups.colorPresetCopyName": "双击复制名称 {value}",
    "groups.colorPresetCopyHex": "双击复制色值 {value}",
    "groups.colorPresetCopied": "已复制 {value}",
    "groups.unifyFontBorderColor": "统一字体与边框颜色",
    "groups.representation": "当前工作流的编组类型",
    "groups.representationWorkspaceKit": "WK 编组",
    "groups.representationNative": "ComfyUI 默认编组",
    "groups.representationHelp": "只作用于当前工作流。转换前会保留 WorkspaceKit 样式和执行状态归档；转换后由 ComfyUI 原生编组负责显示。",
    "groups.convertToNative": "转换为 ComfyUI 默认编组",
    "groups.convertToWorkspaceKit": "转换为 WK 编组",
    "groups.convertToNativeConfirm": "将当前工作流中的 {count} 个 WK 编组转换为 ComfyUI 默认编组？转换前会保留可恢复归档。",
    "groups.convertToWorkspaceKitConfirm": "将当前工作流中的 {count} 个 ComfyUI 默认编组转换为 WK 编组？当前几何与成员关系会保留；历史样式会尽可能恢复。",
    "groups.convertedToNative": "已转换 {count} 个编组。当前工作流现在使用 ComfyUI 默认编组。",
    "groups.convertedToWorkspaceKit": "已转换 {count} 个编组。当前工作流现在使用 WK 编组。",
    "groups.convertFailed": "编组转换失败：{message}",
    "groups.conversionReady": "当前有 {count} 个 WK 编组可转换。",
    "groups.conversionMixed": "当前有 {workspaceKitCount} 个 WK 编组和 {nativeGroupCount} 个 ComfyUI 默认编组；转换会保留已有默认编组。",
    "groups.conversionAlreadyNative": "当前工作流已使用 ComfyUI 默认编组（{count} 个）。",
    "groups.conversionNativeEmpty": "当前工作流没有可转换的 ComfyUI 默认编组。",
    "groups.conversionEmpty": "当前工作流没有可转换的 WK 编组。",
    "groups.conversionLoading": "正在读取当前工作流的编组状态。",
    "groups.convertUnavailableNative": "当前已使用 ComfyUI 默认编组，无需转换。",
    "groups.convertUnavailableNativeEmpty": "当前没有可转换的 ComfyUI 默认编组。",
    "groups.convertUnavailableEmpty": "当前没有可转换的 WK 编组。",
    "groups.convertUnavailableLoading": "编组状态尚未准备完成。",
    "groups.conversionInProgress": "正在转换编组，请稍候。",
    "groups.convertSaveRequired": "请保存当前工作流以写入转换结果。",
    "templates.title": "模板",
    "templates.status": "{count} 个模板",
    "templates.searchPlaceholder": "搜索模板",
    "templates.saveSelected": "保存选中节点为模板",
    "templates.empty": "还没有模板。选择画布上的节点后按 Alt+C 保存。",
    "templates.noMatches": "没有匹配的模板。",
    "templates.promptName": "模板名称",
    "templates.defaultName": "节点模板",
    "templates.saved": "已保存模板：{name}",
    "templates.selectNodesFirst": "请先在画布上选中节点。",
    "templates.canvasUnavailable": "当前画布不可用。",
    "templates.createFailed": "无法创建节点：{type}",
    "templates.restoreMissing": "有 {count} 个节点无法创建：{types}",
    "templates.dropHint": "拖到画布创建模板",
    "templates.pendingPlace": "点击画布放置模板：{name}",
    "templates.meta": "{nodes} 个节点 · {links} 条连线",
    "templates.rename": "重命名",
    "templates.placeCenter": "放置到画布中心",
    "templates.delete": "删除模板",
    "templates.copyName": "复制模板名称",
    "templates.confirmDelete": "删除模板“{name}”？",
    "templates.deleteTitle": "删除模板",
    "templates.deleted": "已删除模板",
    "templates.newGroup": "新建模板分组",
    "templates.defaultGroupName": "新建模板分组",
    "templates.renameGroup": "重命名分组",
    "templates.deleteGroup": "删除分组",
    "templates.confirmDeleteGroup": "删除分组“{name}”？其中的模板会移到模板根位置。",
    "templates.deleteGroupTitle": "删除模板分组",
    "templates.moveToRoot": "移到模板根位置",
    "templates.moveToRootTitle": "拖拽模板到这里，移到模板根位置",
    "templates.emptyGroup": "这个分组还没有模板。",
    "templates.uiScaleTitle": "列表字号",
    "templates.sort.manual": "自定义顺序",
    "templates.sort.nameAsc": "名称 A-Z",
    "templates.sort.nameDesc": "名称 Z-A",
    "templates.sort.updatedDesc": "最近更新",
    "templates.sort.updatedAsc": "最早更新",
    "templates.sortTitle": "模板排序：{sort}。点击打开菜单。",
  },
  "en-US": {
    "workspace.title": "WK Panel",
    "workspace.tooltip": "ComfyUI WorkspaceKit (WK)",
    "workspace.tab.workflows": "Workflows",
    "workspace.tab.nodes": "Nodes",
    "workspace.tab.templates": "Templates",
    "settings.title": "Settings",
    "settings.nav.common": "General",
    "settings.nav.workflows": "Workflows",
    "settings.nav.templates": "Templates",
    "settings.nav.groups": "Groups",
    "settings.nav.shortcuts": "Shortcuts",
    "settings.nav.appearance": "Appearance",
    "settings.nav.advanced": "Advanced",
    "settings.shortcuts": "Shortcuts",
    "settings.behavior": "Open behavior",
    "settings.workflowSettings": "Workflow behavior",
    "settings.templateSettings": "Template behavior",
    "settings.groupSettings": "Groups",
    "settings.groupSettingsHelp": "Manage WorkspaceKit group activation, creation, ungrouping, and pointer gestures in one place.",
    "settings.recentWorkflows": "Open history count",
    "settings.topbarSaveButton": "Show the Save button in the top toolbar",
    "topbar.save": "Save workflow",
    "topbar.saveUnsaved": "Save workflow (unsaved changes)",
    "settings.panelOpacity": "Panel opacity",
    "settings.panelGlass": "Glass background",
    "settings.panelBlur": "Background blur",
    "settings.backgroundEffect": "Background effect",
    "settings.transparentBackground": "Transparent background",
    "settings.glassBackground": "Frosted glass",
    "settings.nodeCache": "Node cache",
    "settings.panelIntegrations": "Plugin integration",
    "settings.statusHelp": "Show bottom status hints",
    "settings.extensionSettings": "Extension settings",
    "settings.panelIntegrationsEnabled": "Allow extension panels to merge",
    "settings.panelIntegrationsHelp": "When disabled, compatible extensions remain separate after the next page refresh. Re-enable and refresh to merge them into WorkspaceKit again.",
    "settings.about": "About",
    "settings.ctrlG": "Enable WorkspaceKit groups",
    "settings.ctrlGHelp": "When enabled, Ctrl+G replaces the ComfyUI default group command.",
    "settings.altCOpenTemplates": "Open Templates after Alt+C saves",
    "settings.closeSameModule": "Close the panel when pressing the current tab shortcut again",
    "settings.shortcuts.workflow": "Workflows panel",
    "settings.shortcuts.nodes": "Nodes panel",
    "settings.shortcuts.templates": "Templates panel",
    "settings.shortcuts.extension": "Pinned extension panel",
    "settings.shortcuts.saveTemplate": "Save template",
    "settings.shortcuts.createGroup": "WorkspaceKit group",
    "settings.shortcuts.ungroup": "Ungroup",
    "settings.shortcuts.shiftLeftClickKey": "Ctrl + Left Click",
    "settings.shortcuts.toggleGroupIgnore": "Toggle group ignore",
    "settings.shortcutsHelp": "Common shortcuts",
    "settings.groupPointerActions.group.disabled": "Disabled",
    "settings.groupPointerRestore": "Restore default gestures",
    "settings.moduleShortcutsHelp": "Disable a shortcut to leave its key combination available to ComfyUI or the browser. Shift + 4 opens the currently pinned extension panel.",
    "settings.moduleShortcuts.workflows": "Enable Shift + 1 (Workflows)",
    "settings.moduleShortcuts.nodes": "Enable Shift + 2 (Nodes)",
    "settings.moduleShortcuts.templates": "Enable Shift + 3 (Templates)",
    "settings.moduleShortcuts.extension": "Enable Shift + 4 (Pinned extension)",
    "settings.cacheCount": "Cached nodes: {count}",
    "settings.cacheUpdated": "Updated: {time}",
    "settings.cacheEmpty": "No cache yet",
    "settings.clearNodeCache": "Clear node cache",
    "settings.nodeCacheCleared": "Node cache cleared",
    "settings.close": "Close",
    "settings.version": "Version: {version}",
    "settings.versionLoading": "Loading…",
    "settings.versionUnavailable": "Unavailable",
    "settings.github": "GitHub: ZiYao00/ComfyUI-WorkspaceKit",
    "confirm.cancel": "Cancel",
    "confirm.dissolve": "Dissolve",
    "confirm.flatten": "Flatten all",
    "confirm.delete": "Delete",
    "confirm.moveToSystemTrash": "Move to system trash",
    "confirm.emptyTrash": "Empty trash",
    "trash.systemDeleteTitle": "Move to system trash",
    "trash.emptyTitle": "Empty WorkspaceKit trash",
    "trash.moveToSystem": "Move All to System Trash",
    "trash.moveAllToSystemShort": "Move All to System Trash",
    "status.folderDissolved": "Folder dissolved",
    "status.folderFlattened": "Folder flattened",
    "status.folderDissolvedRenamed": "Folder dissolved; {count} item(s) were numbered to avoid a name clash",
    "status.folderFlattenedRenamed": "Folder flattened; {count} file(s) were numbered to avoid a name clash",
    "status.systemTrashPartial": "Move to system trash partial: {count} failed. {details}",
    "workflows.title": "Workflows",
    "workflows.current": "Current workflow",
    "workflows.recent": "Open",
    "workflows.browse": "Browse",
    "workflows.view.all": "All",
    "workflows.view.favorites": "Favorites",
    "workflows.addFavorite": "Add workflow to favorites",
    "workflows.removeFavorite": "Remove workflow from favorites",
    "workflows.favoriteAdded": "Workflow added to favorites",
    "workflows.favoriteRemoved": "Workflow removed from favorites",
    "workflows.currentEmpty": "No workflow opened from Workflows2",
    "workflows.removeRecent": "Remove from open history",
    "workflows.close": "Close workflow",
    "workflows.saveCurrent": "Save current workflow",
    "workflows.unsavedChanges": "Unsaved changes",
    "workflows.fileMenu": "File",
    "workflows.fileMenuTitle": "Active workflow file actions",
    "workflows.fileNewWorkflow": "New workflow",
    "workflows.fileNewFolder": "New folder",
    "workflows.fileSave": "Save",
    "workflows.fileSaveAs": "Save As",
    "workflows.fileExport": "Export workflow",
    "workflows.fileExportApi": "Export API workflow",
    "workflows.closeUnsavedTitle": "Close unsaved workflow",
    "workflows.closeUnsavedMessage": "“{name}” has unsaved changes.",
    "workflows.closeSave": "Save and close",
    "workflows.closeDiscard": "Close without saving",
    "toolbar.openWorkflow": "Import",
    "row.copy": "Copy workflow",
    "nodes.title": "Nodes",
    "nodes.status": "{count} nodes",
    "nodes.searchPlaceholder": "Search nodes",
    "nodes.categoryBookmarked": "Favorites",
    "nodes.categoryComfy": "Comfy",
    "nodes.categoryExtensions": "Extensions",
    "nodes.view.bookmarked": "Favorites",
    "nodes.view.comfy": "Comfy",
    "nodes.view.extensions": "Extensions",
    "nodes.moveToFavoriteRoot": "Move to Favorites Root",
    "nodes.moveToFavoriteRootTitle": "Drop a favorite node here to move it to the favorites root",
    "nodes.loadingDefinitions": "Loading node information. Large plugin setups may take a few seconds the first time.",
    "nodes.updatingDefinitions": "Updating full node information in the background...",
    "nodes.officialCategory.3d": "3D",
    "nodes.officialCategory.advanced": "Advanced",
    "nodes.officialCategory.audio": "Audio",
    "nodes.officialCategory.conditioning": "Conditioning",
    "nodes.officialCategory.experimental": "Experimental",
    "nodes.officialCategory.image": "Image",
    "nodes.officialCategory.latent": "Latent",
    "nodes.officialCategory.model": "Model",
    "nodes.officialCategory.text": "Text",
    "nodes.officialCategory.video": "Video",
    "search.placeholder": "Search workflows",
    "root.move": "Move to Root",
    "status.loading": "Loading...",
    "status.error": "Error: {message}",
    "status.openedWorkflowFile": "Opened workflow file",
    "status.workflowSaved": "Workflow saved",
    "status.workflowCopied": "Workflow copied: {name}",
    "status.workflowRenameTargetExists": "Another workflow already uses this name.",
    "status.workflowRenameSourceMissing": "The original workflow file was not found.",
    "status.workflowSaveMismatch": "Only the current open workflow can be saved",
    "status.workflowSerializeUnavailable": "The current ComfyUI frontend does not expose a graph serializer",
    "workflows.sort.nameAsc": "Name A-Z",
    "workflows.sort.nameDesc": "Name Z-A",
    "workflows.sort.updatedDesc": "Newest modified",
    "workflows.sort.updatedAsc": "Oldest modified",
    "workflows.customOrder": "Custom order",
    "workflows.folderFirst": "Folders first",
    "workflows.sortTitle": "Workflow sort: {sort}. Click to open menu.",
    "workflows.sortMenu": "Sort",
    "workflows.reorderHandle": "Drag to reorder",
    "font.size": "List text size",
    "search.clear": "Clear search",
    "nodes.customOrder": "Custom order",
    "nodes.reorderHandle": "Drag to reorder",
    "nodes.defaultGroupName": "New group",
    "nodes.previewEnable": "Enable node preview",
    "nodes.previewDisable": "Disable node preview",
    "nodes.previewOverflowInputs": "{count} more inputs",
    "nodes.previewOverflowWidgets": "{count} more controls",
    "nodes.previewOverflowOutputs": "{count} more outputs",
    "nodes.previewKindImage": "Image",
    "nodes.previewKindAudio": "Audio",
    "nodes.previewKindVideo": "Video",
    "nodes.previewKind3d": "3D",
    "nodes.previewKindText": "Text",
    "nodes.uiScaleTitle": "List text size",
    "nodes.categoryUnknown": "Unknown source",
    "nodes.deleteGroupTitle": "Delete favorite group",
    "nodes.dissolveGroupTitle": "Remove this group and all of its subgroups while keeping their favorite nodes.",
    "nodes.deleteGroupContentsTitle": "Remove this group and cancel all favorite nodes in it and its subgroups.",
    "menu.newSubfolder": "New subfolder",
    "menu.flattenFolder": "Flatten all",
    "row.openLocation": "Show workflow in folder",
    "folder.personalize": "Personalize",
    "folder.dissolveTitle": "Remove this folder while keeping its contents and promoting them one level.",
    "folder.flattenTitle": "Remove this folder and every subfolder inside it, promoting all of their files one level.",
    "folder.deleteTitle": "Move this folder and its contents to the trash.",
    "folder.changeIcon": "Change icon",
    "folder.changeColor": "Change color",
    "folder.resetStyle": "Reset style",
    "folder.personalizeTitle": "Personalize",
    "folder.personalizePreview": "Preview",
    "folder.personalizeIcon": "Icon",
    "folder.personalizeColor": "Color",
    "folder.personalizeApply": "Apply",
    "folder.personalizeReset": "Reset",
    "folder.personalizeCancel": "Cancel",
    "folder.personalizeDefault": "Default",
    "folder.defaultName": "New folder",
    "folder.promptIcon": "Enter a PrimeIcons class, such as pi pi-folder, or an emoji. Leave empty for the default icon.",
    "folder.promptColor": "Enter a color, such as #8ab4f8. Leave empty for the default color.",
    "canvasGroups.title": "Groups",
    "canvasGroups.status": "{count} groups",
    "canvasGroups.searchPlaceholder": "Search groups",
    "canvasGroups.create": "Create group from selected nodes",
    "canvasGroups.refresh": "Refresh group list",
    "canvasGroups.empty": "This workflow has no groups.",
    "canvasGroups.noMatches": "No matching groups.",
    "canvasGroups.nodes": "{count} nodes",
    "canvasGroups.locate": "Locate group",
    "canvasGroups.rename": "Rename group",
    "canvasGroups.promptRename": "Group name",
    "canvasGroups.toggleBypass": "Bypass / restore group",
    "canvasGroups.delete": "Delete group",
    "canvasGroups.confirmDelete": "Delete group \"{name}\"? Nodes will not be deleted.",
    "groups.headerOpacity": "Header",
    "groups.actionRename": "Rename group",
    "groups.backgroundFill": "Background",
    "groups.colorPreset": "Color preset",
    "groups.colorPresetCopyName": "Double-click to copy name {value}",
    "groups.colorPresetCopyHex": "Double-click to copy hex {value}",
    "groups.colorPresetCopied": "Copied {value}",
    "groups.unifyFontBorderColor": "Unify Font and Border Colors",
    "groups.representation": "Current workflow group representation",
    "groups.representationWorkspaceKit": "WK groups",
    "groups.representationNative": "ComfyUI default groups",
    "groups.representationHelp": "Applies only to the current workflow. WorkspaceKit style and execution metadata are archived before conversion; ComfyUI native groups render the result.",
    "groups.convertToNative": "Convert to ComfyUI default groups",
    "groups.convertToWorkspaceKit": "Convert to WK groups",
    "groups.convertToNativeConfirm": "Convert {count} WK groups in the current workflow to ComfyUI default groups? A recoverable archive will be kept first.",
    "groups.convertToWorkspaceKitConfirm": "Convert {count} ComfyUI default groups in the current workflow to WK groups? Current geometry and members are preserved; historical styles are restored when available.",
    "groups.convertedToNative": "Converted {count} groups. This workflow now uses ComfyUI default groups.",
    "groups.convertedToWorkspaceKit": "Converted {count} groups. This workflow now uses WK groups.",
    "groups.convertFailed": "Group conversion failed: {message}",
    "groups.conversionReady": "{count} WK groups are ready to convert.",
    "groups.conversionMixed": "This workflow has {workspaceKitCount} WK groups and {nativeGroupCount} ComfyUI default groups. Existing default groups will be preserved.",
    "groups.conversionAlreadyNative": "This workflow already uses ComfyUI default groups ({count}).",
    "groups.conversionNativeEmpty": "This workflow has no ComfyUI default groups to convert.",
    "groups.conversionEmpty": "This workflow has no WK groups to convert.",
    "groups.conversionLoading": "Reading the current workflow group state.",
    "groups.convertUnavailableNative": "This workflow already uses ComfyUI default groups.",
    "groups.convertUnavailableNativeEmpty": "There are no ComfyUI default groups to convert.",
    "groups.convertUnavailableEmpty": "There are no WK groups to convert.",
    "groups.convertUnavailableLoading": "The group state is not ready yet.",
    "groups.conversionInProgress": "Converting groups. Please wait.",
    "groups.convertSaveRequired": "Save the current workflow to write the conversion result.",
    "templates.title": "Templates",
    "templates.status": "{count} templates",
    "templates.searchPlaceholder": "Search templates",
    "templates.saveSelected": "Save selected nodes as template",
    "templates.empty": "No templates yet. Select canvas nodes and press Alt+C to save.",
    "templates.noMatches": "No matching templates.",
    "templates.promptName": "Template name",
    "templates.defaultName": "Node template",
    "templates.saved": "Saved template: {name}",
    "templates.selectNodesFirst": "Select nodes on the canvas first.",
    "templates.canvasUnavailable": "Canvas is not available.",
    "templates.createFailed": "Could not create node: {type}",
    "templates.restoreMissing": "{count} nodes could not be created: {types}",
    "templates.dropHint": "Drag to canvas to create template",
    "templates.pendingPlace": "Click the canvas to place template: {name}",
    "templates.meta": "{nodes} nodes · {links} links",
    "templates.rename": "Rename",
    "templates.placeCenter": "Place at canvas center",
    "templates.delete": "Delete template",
    "templates.copyName": "Copy template name",
    "templates.confirmDelete": "Delete template \"{name}\"?",
    "templates.deleteTitle": "Delete template",
    "templates.deleted": "Deleted template",
    "templates.newGroup": "New template group",
    "templates.defaultGroupName": "New template group",
    "templates.renameGroup": "Rename group",
    "templates.deleteGroup": "Delete group",
    "templates.confirmDeleteGroup": "Delete group \"{name}\"? Templates in it will move to the template root.",
    "templates.deleteGroupTitle": "Delete template group",
    "templates.moveToRoot": "Move to Template Root",
    "templates.moveToRootTitle": "Drop a template here to move it to the template root",
    "templates.emptyGroup": "No templates in this group.",
    "templates.uiScaleTitle": "List text size",
    "templates.sort.manual": "Custom order",
    "templates.sort.nameAsc": "Name A-Z",
    "templates.sort.nameDesc": "Name Z-A",
    "templates.sort.updatedDesc": "Recently updated",
    "templates.sort.updatedAsc": "Oldest updated",
    "templates.sortTitle": "Template sort: {sort}. Click to open menu.",
  },
};
